# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

release-once-merged:
- changed-files:
  - any-glob-to-any-file:
    - microsoft-graph/**/*
    - resource-manager/**/*
    - sdk/**/*