name: Open Pull Request when an `auto-pr` is pushed
on:
  push:
    branches:
      - 'auto-pr/**'

jobs:
  open-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "open a pull request"
        id: open-pr
        run: |
          bash ./scripts/open-pull-request.sh "$PR_TITLE" "$PR_BODY" "$PR_TARGET" "$PR_LABEL"

        env:
          PR_TITLE: "Auto PR: Regenerating the Go SDK (${{ github.sha }})"
          PR_BODY: "Regenerating the SDK based on the latest changes"
          PR_TARGET: "main"
          PR_LABEL: "release-once-merged"
          GITHUB_TOKEN: ${{ secrets.SERVICE_ACCOUNT_GO_SDK_TOKEN }}
