---
name: Unit Tests
on:
  pull_request:
    types: ['opened', 'synchronize']

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version: '1.19.5'

      - name: Run unit tests
        run: make test

# vim: set ts=2 sts=2 sw=2 et:
